robot_list_request_body:
  robotServiceSkillSumRate_api: /plat/api/report/work/robotServiceSkillSumRate
  sumExecuteTask_api: /plat/api/report/work/sumExecuteTask
  sumTask_api: /plat/api/report/work/sumTask
  queryExeTaskListByCon_api: /plat/api/exeTask/queryExeTaskListByCon
  queryDispatchTaskListByCon_api: /plat/api/task/queryDispatchTaskListByCon
  sumExecuteMonthTask_api: /plat/api/report/work/sumExecuteMonthTask


  request_header: {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36',
    'Content-Type': 'application/json;charset=UTF-8',
    'Cookie': 'SESSION=NWYzYTgxOGQtN2E2Ny00ODJjLWE4ZWQtNmFkNTAwNjAyMTJh'
  }


query_data_payload:
  {
    pageIndex: 1,
    pageSize: 10
  }

sumExecuteMonthTask_payload:
  {
    year: 2023,
    month:,
    day:,
    hour:
  }
