pipeline{
    agent any
    stages{
        stage("first"){
            steps {
                sh 'cd run_main && python3 main.py'
            }
        }
    }
    post{
        always{
            echo 'always say goodbay'
        }
    }
}